name: 'Schema Validation'
description: 'Confluent Cloud schema registry compatibility check'
branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  avro-subject-yaml:
    description: 'path to the subject file'
    required: false
    default: 'schemas.yaml'
  avro-files-path:
    description: 'path to the schemas folder'
    required: false
    default: 'src/main/avro'
  schema-registry-url:
    description: 'url to the schema-registry'
    required: true
  schema-registry-api-key:
    description: 'Confluent API key'
    required: true
  schema-registry-secret-key:
    description: 'Confluent secret key'
    required: true

runs:
  using: 'docker'
  image: 'docker://loicmdivad/ccloud-registry-action:v0.0.1'
  env:
    AVRO_FILES_PATH: ${{ inputs.avro-files-path }}
    AVRO_SUBJECT_YAML: ${{ inputs.avro-subject-yaml }}
    SCHEMA_REGISTRY_URL: ${{ inputs.schema-registry-url }}
    SCHEMA_REGISTRY_API_KEY: ${{ inputs.schema-registry-api-key }}
    SCHEMA_REGISTRY_SECRET_KEY: ${{ inputs.schema-registry-secret-key }}
